<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x86;x64;ARM64;AnyCPU</Platforms>
    <SupportedOSPlatform>windows</SupportedOSPlatform>
    <NoWarn>$(NoWarn);MVVMTK0045</NoWarn>
  </PropertyGroup>
</Project>
